using System.Text.RegularExpressions;

namespace AdventOfCode2022
{
    internal class Day5
    {
        private static readonly string[] Data =
        {
            "[J]             [F] [M]            ",
            "[Z] [F]     [G] [Q] [F]            ",
            "[G] [P]     [H] [Z] [S] [Q]        ",
            "[V] [W] [Z] [P] [D] [G] [P]        ",
            "[T] [D] [S] [Z] [N] [W] [B] [N]    ",
            "[D] [M] [R] [J] [J] [P] [V] [P] [J]",
            "[B] [R] [C] [T] [C] [V] [C] [B] [P]",
            "[N] [S] [V] [R] [T] [N] [G] [Z] [W]",
            " 1   2   3   4   5   6   7   8   9 ",
            "",
            "move 2 from 4 to 6",
            "move 1 from 9 to 5",
            "move 3 from 2 to 4",
            "move 8 from 4 to 7",
            "move 2 from 9 to 7",
            "move 3 from 8 to 3",
            "move 2 from 1 to 2",
            "move 5 from 7 to 9",
            "move 1 from 9 to 4",
            "move 1 from 8 to 3",
            "move 1 from 3 to 4",
            "move 2 from 4 to 9",
            "move 7 from 3 to 5",
            "move 6 from 1 to 8",
            "move 11 from 7 to 9",
            "move 12 from 5 to 3",
            "move 6 from 6 to 9",
            "move 3 from 3 to 8",
            "move 4 from 2 to 7",
            "move 3 from 5 to 7",
            "move 1 from 5 to 7",
            "move 2 from 2 to 5",
            "move 1 from 5 to 2",
            "move 5 from 8 to 9",
            "move 7 from 7 to 2",
            "move 3 from 8 to 7",
            "move 1 from 8 to 9",
            "move 4 from 3 to 6",
            "move 1 from 5 to 1",
            "move 9 from 9 to 6",
            "move 7 from 9 to 6",
            "move 20 from 6 to 5",
            "move 12 from 9 to 8",
            "move 5 from 5 to 1",
            "move 3 from 7 to 4",
            "move 6 from 2 to 7",
            "move 2 from 3 to 1",
            "move 4 from 3 to 8",
            "move 1 from 4 to 1",
            "move 7 from 7 to 5",
            "move 4 from 8 to 2",
            "move 3 from 6 to 2",
            "move 3 from 2 to 9",
            "move 4 from 1 to 7",
            "move 2 from 1 to 2",
            "move 3 from 9 to 5",
            "move 11 from 8 to 5",
            "move 1 from 6 to 9",
            "move 1 from 8 to 5",
            "move 1 from 1 to 2",
            "move 24 from 5 to 4",
            "move 2 from 1 to 6",
            "move 11 from 5 to 4",
            "move 2 from 7 to 9",
            "move 1 from 6 to 2",
            "move 4 from 2 to 1",
            "move 28 from 4 to 2",
            "move 1 from 7 to 8",
            "move 9 from 2 to 5",
            "move 2 from 9 to 6",
            "move 4 from 4 to 2",
            "move 1 from 7 to 4",
            "move 3 from 4 to 7",
            "move 1 from 6 to 9",
            "move 21 from 2 to 3",
            "move 3 from 1 to 6",
            "move 5 from 6 to 2",
            "move 7 from 2 to 3",
            "move 1 from 9 to 3",
            "move 1 from 8 to 4",
            "move 1 from 7 to 8",
            "move 3 from 5 to 8",
            "move 1 from 1 to 7",
            "move 2 from 7 to 9",
            "move 2 from 8 to 4",
            "move 1 from 9 to 2",
            "move 1 from 8 to 6",
            "move 11 from 3 to 4",
            "move 1 from 7 to 8",
            "move 6 from 5 to 9",
            "move 2 from 8 to 7",
            "move 1 from 6 to 5",
            "move 7 from 3 to 8",
            "move 9 from 3 to 6",
            "move 1 from 8 to 3",
            "move 1 from 7 to 4",
            "move 2 from 3 to 5",
            "move 4 from 5 to 7",
            "move 4 from 6 to 8",
            "move 2 from 7 to 9",
            "move 11 from 4 to 2",
            "move 1 from 4 to 2",
            "move 6 from 8 to 9",
            "move 1 from 7 to 1",
            "move 1 from 3 to 7",
            "move 3 from 7 to 8",
            "move 6 from 8 to 9",
            "move 6 from 4 to 8",
            "move 18 from 9 to 3",
            "move 1 from 5 to 8",
            "move 5 from 6 to 5",
            "move 6 from 8 to 1",
            "move 3 from 5 to 4",
            "move 1 from 9 to 8",
            "move 3 from 4 to 8",
            "move 15 from 3 to 6",
            "move 2 from 5 to 9",
            "move 3 from 3 to 1",
            "move 9 from 6 to 4",
            "move 2 from 1 to 5",
            "move 2 from 5 to 8",
            "move 6 from 4 to 2",
            "move 6 from 1 to 6",
            "move 3 from 4 to 6",
            "move 6 from 9 to 1",
            "move 4 from 2 to 1",
            "move 7 from 8 to 1",
            "move 1 from 6 to 7",
            "move 17 from 1 to 5",
            "move 1 from 7 to 1",
            "move 5 from 2 to 1",
            "move 1 from 8 to 6",
            "move 11 from 6 to 4",
            "move 2 from 2 to 3",
            "move 3 from 1 to 8",
            "move 7 from 2 to 5",
            "move 4 from 6 to 7",
            "move 4 from 1 to 5",
            "move 15 from 5 to 9",
            "move 2 from 3 to 7",
            "move 2 from 8 to 2",
            "move 1 from 1 to 9",
            "move 6 from 2 to 6",
            "move 7 from 5 to 6",
            "move 5 from 7 to 3",
            "move 1 from 6 to 1",
            "move 2 from 3 to 4",
            "move 1 from 3 to 4",
            "move 5 from 6 to 4",
            "move 14 from 9 to 2",
            "move 1 from 8 to 9",
            "move 1 from 7 to 8",
            "move 1 from 9 to 6",
            "move 2 from 9 to 5",
            "move 1 from 1 to 2",
            "move 7 from 6 to 9",
            "move 1 from 3 to 4",
            "move 8 from 5 to 2",
            "move 1 from 6 to 7",
            "move 1 from 7 to 4",
            "move 1 from 8 to 4",
            "move 1 from 3 to 9",
            "move 7 from 9 to 5",
            "move 1 from 9 to 1",
            "move 6 from 5 to 1",
            "move 8 from 2 to 4",
            "move 1 from 5 to 6",
            "move 1 from 6 to 7",
            "move 1 from 7 to 9",
            "move 7 from 2 to 9",
            "move 1 from 9 to 4",
            "move 3 from 9 to 1",
            "move 1 from 9 to 6",
            "move 11 from 2 to 8",
            "move 9 from 1 to 8",
            "move 1 from 6 to 4",
            "move 1 from 1 to 9",
            "move 12 from 4 to 2",
            "move 4 from 9 to 3",
            "move 3 from 4 to 6",
            "move 9 from 8 to 6",
            "move 12 from 4 to 9",
            "move 8 from 6 to 3",
            "move 8 from 2 to 7",
            "move 11 from 3 to 4",
            "move 2 from 2 to 7",
            "move 2 from 6 to 1",
            "move 1 from 2 to 3",
            "move 2 from 6 to 2",
            "move 3 from 2 to 6",
            "move 2 from 1 to 6",
            "move 1 from 6 to 1",
            "move 1 from 6 to 4",
            "move 2 from 6 to 3",
            "move 1 from 6 to 5",
            "move 4 from 3 to 8",
            "move 12 from 4 to 5",
            "move 5 from 9 to 7",
            "move 3 from 8 to 7",
            "move 1 from 9 to 1",
            "move 3 from 8 to 2",
            "move 13 from 5 to 6",
            "move 1 from 2 to 9",
            "move 13 from 6 to 7",
            "move 7 from 9 to 6",
            "move 2 from 4 to 6",
            "move 1 from 8 to 6",
            "move 1 from 1 to 6",
            "move 1 from 2 to 9",
            "move 1 from 2 to 3",
            "move 12 from 7 to 9",
            "move 7 from 8 to 4",
            "move 1 from 1 to 3",
            "move 2 from 7 to 9",
            "move 15 from 7 to 4",
            "move 8 from 6 to 3",
            "move 1 from 8 to 9",
            "move 1 from 7 to 2",
            "move 10 from 3 to 5",
            "move 6 from 5 to 9",
            "move 1 from 2 to 8",
            "move 1 from 5 to 8",
            "move 2 from 8 to 9",
            "move 10 from 4 to 9",
            "move 20 from 9 to 6",
            "move 1 from 7 to 6",
            "move 4 from 9 to 3",
            "move 1 from 5 to 9",
            "move 4 from 4 to 9",
            "move 8 from 9 to 7",
            "move 2 from 5 to 1",
            "move 7 from 4 to 3",
            "move 8 from 3 to 2",
            "move 6 from 9 to 8",
            "move 1 from 3 to 7",
            "move 1 from 3 to 1",
            "move 7 from 7 to 8",
            "move 13 from 8 to 3",
            "move 2 from 2 to 8",
            "move 1 from 8 to 2",
            "move 1 from 4 to 1",
            "move 1 from 1 to 8",
            "move 2 from 8 to 2",
            "move 24 from 6 to 2",
            "move 2 from 7 to 8",
            "move 5 from 3 to 4",
            "move 25 from 2 to 6",
            "move 5 from 4 to 9",
            "move 2 from 8 to 7",
            "move 2 from 7 to 3",
            "move 4 from 6 to 2",
            "move 2 from 6 to 4",
            "move 9 from 2 to 3",
            "move 11 from 3 to 7",
            "move 10 from 7 to 8",
            "move 1 from 7 to 9",
            "move 3 from 2 to 4",
            "move 8 from 8 to 2",
            "move 1 from 2 to 6",
            "move 2 from 4 to 1",
            "move 1 from 8 to 2",
            "move 1 from 6 to 9",
            "move 1 from 8 to 3",
            "move 6 from 9 to 7",
            "move 2 from 9 to 1",
            "move 9 from 6 to 8",
            "move 7 from 2 to 3",
            "move 7 from 8 to 2",
            "move 10 from 6 to 8",
            "move 7 from 1 to 2",
            "move 9 from 3 to 2",
            "move 5 from 3 to 8",
            "move 4 from 7 to 2",
            "move 2 from 3 to 2",
            "move 12 from 2 to 3",
            "move 6 from 4 to 2",
            "move 1 from 7 to 6",
            "move 5 from 3 to 5",
            "move 16 from 8 to 4",
            "move 12 from 2 to 7",
            "move 5 from 5 to 7",
            "move 1 from 8 to 3",
            "move 1 from 6 to 4",
            "move 17 from 7 to 4",
            "move 1 from 7 to 1",
            "move 1 from 1 to 9",
            "move 1 from 9 to 5",
            "move 11 from 4 to 9",
            "move 10 from 2 to 3",
            "move 1 from 5 to 4",
            "move 1 from 9 to 2",
            "move 2 from 2 to 1",
            "move 1 from 2 to 3",
            "move 23 from 4 to 5",
            "move 7 from 9 to 7",
            "move 3 from 9 to 1",
            "move 20 from 5 to 6",
            "move 3 from 5 to 8",
            "move 1 from 4 to 1",
            "move 2 from 8 to 3",
            "move 4 from 6 to 4",
            "move 7 from 7 to 2",
            "move 1 from 8 to 4",
            "move 19 from 3 to 9",
            "move 5 from 1 to 7",
            "move 7 from 2 to 6",
            "move 3 from 7 to 5",
            "move 2 from 3 to 4",
            "move 1 from 5 to 4",
            "move 1 from 1 to 4",
            "move 1 from 7 to 6",
            "move 13 from 6 to 7",
            "move 6 from 9 to 3",
            "move 1 from 3 to 5",
            "move 2 from 3 to 4",
            "move 2 from 6 to 2",
            "move 3 from 4 to 3",
            "move 8 from 9 to 1",
            "move 2 from 2 to 1",
            "move 8 from 6 to 7",
            "move 2 from 9 to 4",
            "move 20 from 7 to 1",
            "move 2 from 7 to 5",
            "move 2 from 5 to 1",
            "move 8 from 1 to 8",
            "move 8 from 8 to 6",
            "move 1 from 6 to 9",
            "move 8 from 6 to 1",
            "move 1 from 5 to 3",
            "move 7 from 3 to 2",
            "move 1 from 5 to 2",
            "move 2 from 9 to 7",
            "move 1 from 5 to 8",
            "move 18 from 1 to 4",
            "move 1 from 8 to 9",
            "move 3 from 2 to 3",
            "move 2 from 7 to 4",
            "move 5 from 2 to 4",
            "move 3 from 3 to 8",
            "move 8 from 1 to 7",
            "move 2 from 9 to 2",
            "move 32 from 4 to 5",
            "move 1 from 9 to 7",
            "move 1 from 2 to 1",
            "move 6 from 1 to 6",
            "move 1 from 2 to 4",
            "move 3 from 8 to 1",
            "move 3 from 6 to 5",
            "move 1 from 3 to 6",
            "move 2 from 1 to 9",
            "move 4 from 4 to 7",
            "move 31 from 5 to 4",
            "move 4 from 5 to 6",
            "move 1 from 6 to 1",
            "move 7 from 6 to 5",
            "move 1 from 9 to 4",
            "move 19 from 4 to 2",
            "move 1 from 5 to 9",
            "move 5 from 5 to 6",
            "move 3 from 4 to 2",
            "move 2 from 7 to 1",
            "move 4 from 7 to 8",
            "move 3 from 8 to 6",
            "move 2 from 6 to 7",
            "move 6 from 7 to 8",
            "move 3 from 1 to 5",
            "move 4 from 5 to 9",
            "move 15 from 2 to 1",
            "move 4 from 6 to 4",
            "move 2 from 6 to 3",
            "move 1 from 3 to 7",
            "move 4 from 1 to 2",
            "move 1 from 3 to 4",
            "move 2 from 7 to 4",
            "move 5 from 9 to 3",
            "move 2 from 7 to 3",
            "move 16 from 4 to 8",
            "move 8 from 8 to 5",
            "move 2 from 1 to 5",
            "move 1 from 9 to 6",
            "move 1 from 6 to 5",
            "move 7 from 5 to 9",
            "move 3 from 1 to 8",
            "move 1 from 8 to 4",
            "move 8 from 2 to 7",
            "move 3 from 1 to 3",
            "move 1 from 3 to 9",
            "move 2 from 4 to 2",
            "move 7 from 8 to 5",
            "move 7 from 9 to 1",
            "move 6 from 3 to 5",
            "move 6 from 7 to 4",
            "move 3 from 4 to 1",
            "move 3 from 2 to 5",
            "move 1 from 7 to 8",
            "move 1 from 7 to 5",
            "move 1 from 9 to 8",
            "move 2 from 2 to 4",
            "move 15 from 1 to 6",
            "move 8 from 5 to 9",
            "move 3 from 3 to 4",
            "move 4 from 4 to 3",
            "move 1 from 9 to 7",
            "move 6 from 9 to 4",
            "move 1 from 9 to 2",
            "move 6 from 4 to 9",
            "move 2 from 4 to 6",
            "move 5 from 6 to 9",
            "move 1 from 3 to 1",
            "move 8 from 6 to 8",
            "move 12 from 5 to 3",
            "move 1 from 5 to 3",
            "move 1 from 3 to 8",
            "move 4 from 6 to 1",
            "move 11 from 3 to 8",
            "move 1 from 2 to 1",
            "move 23 from 8 to 2",
            "move 3 from 1 to 2",
            "move 1 from 1 to 9",
            "move 2 from 2 to 3",
            "move 6 from 3 to 6",
            "move 1 from 7 to 6",
            "move 1 from 4 to 7",
            "move 1 from 4 to 3",
            "move 1 from 7 to 3",
            "move 4 from 8 to 4",
            "move 2 from 1 to 8",
            "move 3 from 8 to 1",
            "move 4 from 6 to 2",
            "move 7 from 9 to 1",
            "move 1 from 9 to 6",
            "move 2 from 2 to 3",
            "move 3 from 9 to 4",
            "move 1 from 9 to 3",
            "move 10 from 2 to 8",
            "move 16 from 2 to 5",
            "move 2 from 3 to 6",
            "move 6 from 1 to 8",
            "move 1 from 1 to 5",
            "move 8 from 8 to 5",
            "move 11 from 5 to 9",
            "move 2 from 1 to 8",
            "move 1 from 1 to 8",
            "move 4 from 4 to 6",
            "move 3 from 3 to 9",
            "move 14 from 9 to 3",
            "move 15 from 8 to 5",
            "move 9 from 5 to 4",
            "move 7 from 6 to 1",
            "move 1 from 6 to 3",
            "move 4 from 4 to 7",
            "move 2 from 6 to 2",
            "move 4 from 7 to 4",
            "move 4 from 1 to 4",
            "move 10 from 4 to 3",
            "move 14 from 3 to 6",
            "move 5 from 4 to 1",
            "move 6 from 5 to 7",
            "move 1 from 2 to 6",
            "move 3 from 7 to 2",
            "move 2 from 2 to 3",
            "move 3 from 7 to 8",
            "move 2 from 8 to 2",
            "move 2 from 2 to 7",
            "move 6 from 6 to 2",
            "move 1 from 8 to 7",
            "move 8 from 2 to 7",
            "move 1 from 4 to 1",
            "move 5 from 5 to 3",
            "move 3 from 3 to 2",
            "move 5 from 1 to 3",
            "move 7 from 5 to 8",
            "move 6 from 6 to 3",
            "move 1 from 5 to 9",
            "move 10 from 7 to 9",
            "move 26 from 3 to 4",
            "move 1 from 5 to 1",
            "move 6 from 8 to 2",
            "move 9 from 2 to 9",
            "move 1 from 7 to 5",
            "move 1 from 8 to 5",
            "move 2 from 6 to 2",
            "move 20 from 9 to 6",
            "move 1 from 1 to 6",
            "move 1 from 4 to 2",
            "move 1 from 5 to 8",
            "move 1 from 5 to 7",
            "move 3 from 1 to 3",
            "move 1 from 3 to 6",
            "move 12 from 4 to 8",
            "move 11 from 4 to 5",
            "move 1 from 7 to 5",
            "move 1 from 2 to 8",
            "move 1 from 1 to 8",
            "move 2 from 2 to 5",
            "move 8 from 6 to 2",
            "move 5 from 6 to 4",
            "move 2 from 5 to 3",
            "move 12 from 8 to 4",
            "move 5 from 2 to 6",
            "move 3 from 8 to 1",
            "move 11 from 6 to 8",
            "move 10 from 4 to 6",
            "move 5 from 4 to 6",
            "move 12 from 6 to 5",
            "move 22 from 5 to 6",
            "move 3 from 6 to 5",
            "move 3 from 8 to 5",
            "move 1 from 3 to 8",
            "move 4 from 8 to 1",
            "move 6 from 1 to 7",
            "move 5 from 6 to 9"
        };

        public static void Run()
        {
            Regex rx = new Regex(@"move\s(\d+)\sfrom\s(\d+)\sto\s(\d+)");

            Dictionary<int, Stack<char>> stacks = new();

            for (int part = 1; part <= 2; part++)
            {
                stacks.Clear();

                int i = 0;

                for (; i < Data.Length && !string.IsNullOrWhiteSpace(Data[i]); i++)
                {
                    if (Data[i].Contains('['))
                    {
                        for (int j = 0; Data[i].Length > j + 2; j += 4)
                        {
                            if (Data[i][j] == '[' && Data[i][j + 2] == ']')
                            {
                                if (!stacks.ContainsKey(j / 4 + 1))
                                {
                                    stacks.Add(j / 4 + 1, new Stack<char>());
                                }

                                stacks[j / 4 + 1].Push(Data[i][j + 1]);
                            }
                        }
                    }
                }

                // invert the stacks...
                foreach (int k in stacks.Keys)
                {
                    stacks[k] = new Stack<char>(stacks[k]);
                }

                for (; i < Data.Length; i++)
                {
                    Match mx = rx.Match(Data[i]);

                    if (mx.Success & mx.Groups.Count == 3 + 1)
                    {
                        int count = int.Parse(mx.Groups[1].Value);
                        int from = int.Parse(mx.Groups[2].Value);
                        int to = int.Parse(mx.Groups[3].Value);

                        if (part == 1)
                        {
                            for (int c = 0; c < count; c++)
                            {
                                stacks[to].Push(stacks[from].Pop());
                            }
                        }
                        else
                        {
                            Stack<char> tempStack = new();

                            for (int c = 0; c < count; c++)
                            {
                                tempStack.Push(stacks[from].Pop());
                            }

                            for (int c = 0; c < count; c++)
                            {
                                stacks[to].Push(tempStack.Pop());
                            }
                        }
                    }
                }

                Console.WriteLine($"Day 5 Part {part} Stack tops are {stacks.OrderBy(s => s.Key).Select(s => s.Value.Peek()).Aggregate("", (current, next) => current + next)}.");
            }

        }
    }
}